### ISSUE TITLE
使用less报错

### ISSUE THREAD

**Issue by hanwensheng666** [NervJS/tarojs-plugin-ssr#24]
引入其他npm包，报错：
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/34360878/233975207-fc707909-9109-450a-bf34-e044f8f14483.png">

/../node_modules/@baidu/med-styles/lib/wise.less
Module parse failed: Unexpected character '@' (6:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * @Date: 2021-05-07 21:46:11 
|  */
>  @import './color/class.less';
|  @import './font/class.less';
|  @import './layout/class.less';

Import trace for requested module:
../../node_modules/@baidu/med-styles/lib/wise.less
c

**Comment by liuhuapiaoyuan** [comment]
咋处理呀
