### ISSUE TITLE
taro image 为什么要用div 背景图实现呢，而且 style 还设置了固定尺寸

### ISSUE THREAD

**Issue by JohnApache** [NervJS/tarojs-plugin-ssr#26]
taro image 为什么要用背景图实现呢，而且 style 还设置了固定尺寸,  每个图片都必须设置宽高才能正常显示

**Comment by SyMind** [comment]
@JohnApache 采用 baidu 小程序 web 化的实现方案，这样实现是存在哪些地方与微信小程序的表现不一致么？

**Comment by JohnApache** [comment]
微信小程序默认图片也不会有固定尺寸吧 ？&nbsp; 现在的插件里内置的图片组件包含有固定尺寸，&nbsp; &nbsp;而官方 taro-h5的提供的组件&nbsp; 是用img写的&nbsp; 也不会有一个固定的宽高样式。&nbsp; &nbsp; &nbsp; 我这边遇到的问题是在做瀑布流样式的时候设置图片widthfix，希望高度正常自适应，单刷现在显示不太正常的， 看了下源码查到现在这个插件提供的image是用backgroundimage实现的&nbsp; &nbsp; &nbsp;不明白为什么这里一定需要用bg实现图片&nbsp; &nbsp;用img不会更好吗&nbsp; &nbsp; &nbsp;？



---原始邮件---
发件人: "Cong-Cong ***@***.***&gt;
发送时间: 2023年7月12日(周三) 晚上9:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NervJS/tarojs-plugin-ssr] taro image 为什么要用div 背景图实现呢，而且 style 还设置了固定尺寸 (Issue #26)




 
@JohnApache 采用 baidu 小程序 web 化的实现方案，这样实现是存在哪些地方与微信小程序的表现不一致么？

**Comment by SyMind** [comment]
@JohnApache ok，我将在本周末查看该问题，你有兴趣帮助我实现么？

**Comment by JohnApache** [comment]
我们本地打算用的这个插件改造这里&nbsp; 我们本地验证没问题&nbsp; 到时候可以提一个pr&nbsp; 跟你们同步下&nbsp;



---原始邮件---
发件人: "Cong-Cong ***@***.***&gt;
发送时间: 2023年7月12日(周三) 晚上11:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NervJS/tarojs-plugin-ssr] taro image 为什么要用div 背景图实现呢，而且 style 还设置了固定尺寸 (Issue #26)




 
@JohnApache ok，我将在本周末查看该问题，你有兴趣帮助我实现么？

**Comment by SyMind** [comment]
非常期待你的同步。

**Comment by SyMind** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/image.html
我看微信小程序在 h5 端的实现也是使用 div + background-image 实现的，这样看来实际上是 taro 的实现不够贴合小程序。
