### ISSUE TITLE
tarojs_plugin_platform_nextjs_taro__WEBPACK_IMPORTED_MODULE_0__.useLaunch) is not a function

### ISSUE THREAD

**Issue by xuganggit** [NervJS/tarojs-plugin-ssr#31]
nodejs@14.21.3 + Taro@3.6.13
nodejs@16.20.2 + Taro@3.6.15
项目跑起来后报标题所示的错误，页面内的钩子：useLoad也会报类似的错误，注释了之后可以运行：
![ex2](https://github.com/NervJS/tarojs-plugin-ssr/assets/44916998/f04a623d-767d-49e3-b19a-3109c6685702)
![ex3](https://github.com/NervJS/tarojs-plugin-ssr/assets/44916998/188bfb13-a25b-411a-80c4-cff77af51450)

**Comment by SyMind** [comment]
@xuganggit 插件的版本是什么？[2.0.13](https://github.com/NervJS/tarojs-plugin-ssr/releases/tag/v2.0.13) 才对 Taro v3.5.0+ 新增的 Hook 进行支持。

**Comment by xuganggit** [comment]
嗯嗯，之前安的是2.0.0，用2.0.13可以了

**Comment by xuganggit** [comment]
使用2.1.0或2.1.2版本运行起来之后报这个错：
![ex4](https://github.com/NervJS/tarojs-plugin-ssr/assets/44916998/70e1efad-aad3-4202-b1fd-c233755ab600)

**Comment by jiaming0709** [comment]
<img width="875" alt="image" src="https://github.com/NervJS/tarojs-plugin-ssr/assets/14344815/6432769c-7311-4deb-bdec-2e5d6b9ee2b3">

 插件版本更新为2.0.13，然后taro版本为3.6.8 nodejs版本为V18.17.1 报这个错

**Comment by CongCong262** [comment]
@xuganggit 如果插件的最新版本没有问题的话就先忽略它。可能是插件老版本本身的问题，可能是 Taro 版本每次迭代都会导致一些差异导致。

**Comment by CongCong262** [comment]
@jiaming0709 我将在本周三前查看该问题。

**Comment by SyMind** [comment]
@xuganggit 如果插件的最新版本没有问题的话就先忽略它。可能是插件老版本本身的问题，可能是 Taro 版本每次迭代都会导致一些差异导致。

**Comment by SyMind** [comment]
@jiaming0709 我将在本周三前查看该问题。

**Comment by jiaming0709** [comment]
> 



> @jiaming0709 我将在本周三前查看该问题。

装了typescript后，这个问题就解决了
