### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by niujunhui** [NervJS/tarojs-plugin-ssr#34]
项目启动起来后报这个错，有没有人遇得到？怎么解决

**Comment by SyMind** [comment]
可能是使用的某些依赖不支持 CommonJS 版本，导致在 Next.js 服务端执行报错。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: niujunhui ***@***.***>
发送时间: Tuesday, September 12, 2023 10:03:40 AM
收件人: NervJS/tarojs-plugin-ssr ***@***.***>
抄送: Subscribed ***@***.***>
主题: [NervJS/tarojs-plugin-ssr] SyntaxError: Cannot use import statement outside a module (Issue #34)


项目启动起来后报这个错，有没有人遇得到？怎么解决

―
