### ISSUE TITLE
执行 npx taro build --type nextjs --watch报错 TypeError: Cannot read properties of undefined (reading 'backgroundColor')

### ISSUE THREAD

**Issue by garminy** [NervJS/tarojs-plugin-ssr#39]
![WX20240119-162643@2x](https://github.com/NervJS/tarojs-plugin-ssr/assets/14344815/88523fa1-86e9-4edb-8fca-6e798c5ee782)

**Comment by garminy** [comment]
Node.js v18.17.1
Taro v3.6.8

**Comment by garminy** [comment]
tarojs-plugin-platform-nextjs 2.1.4
Node.js v18.17.1
Taro v3.6.8

我在npm包报错的位置加了几行log,
<img width="1185" alt="image" src="https://github.com/NervJS/tarojs-plugin-ssr/assets/14344815/55cf8085-d06b-4a04-9165-46795d9ada89">
<img width="1067" alt="image" src="https://github.com/NervJS/tarojs-plugin-ssr/assets/14344815/930f3d7b-42f1-4f9b-b0a5-1e81303e483d">

打印后发现eval(code) 获取到的是undefined

**Comment by SyMind** [comment]
@garminy 感谢反馈，已修复。
